<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Midora.Desktop.Presentation</AssemblyName>
    <RootNamespace>Midora.Desktop.Presentation</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\midora-core\Midora.Domain\Midora.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="..\Midora.Desktop.StyleGallery\Themes\Palette.xaml"
          Link="Themes\Palette.xaml" />
    <Page Include="..\Midora.Desktop.StyleGallery\Themes\FluentSystemIcons.xaml"
          Link="Themes\FluentSystemIcons.xaml" />
    <Page Include="..\Midora.Desktop.StyleGallery\Themes\WindowControlIcons.xaml"
          Link="Themes\WindowControlIcons.xaml" />
    <Page Include="..\Midora.Desktop.StyleGallery\Themes\Controls.xaml"
          Link="Themes\Controls.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\..\assets\fonts\Sora\Sora-Light.ttf"
              Link="Assets\Fonts\Sora\Sora-Light.ttf" />
    <Resource Include="..\..\..\assets\fonts\Sora\Sora-Regular.ttf"
              Link="Assets\Fonts\Sora\Sora-Regular.ttf" />
    <Resource Include="..\..\..\assets\fonts\Sora\Sora-SemiBold.ttf"
              Link="Assets\Fonts\Sora\Sora-SemiBold.ttf" />
    <Resource Include="..\..\..\assets\fonts\Sora\Sora-Bold.ttf"
              Link="Assets\Fonts\Sora\Sora-Bold.ttf" />
    <Resource Include="..\..\..\assets\fonts\JetBrainsMono\JetBrainsMono-Regular.ttf"
              Link="Assets\Fonts\JetBrainsMono\JetBrainsMono-Regular.ttf" />
    <Resource Include="..\..\..\assets\fonts\JetBrainsMono\JetBrainsMono-SemiBold.ttf"
              Link="Assets\Fonts\JetBrainsMono\JetBrainsMono-SemiBold.ttf" />
    <Resource Include="..\..\..\assets\fonts\JetBrainsMono\JetBrainsMono-Bold.ttf"
              Link="Assets\Fonts\JetBrainsMono\JetBrainsMono-Bold.ttf" />
  </ItemGroup>
</Project>
