<Project>
    <Import Project="$(MSBuildThisFileDirectory)eng\Version.props" />
    <PropertyGroup>                
        <Nullable>enable</Nullable>
        <Deterministic>true</Deterministic>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
        <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningsAsErrors>$(WarningsAsErrors);nullable</WarningsAsErrors>
    </PropertyGroup>
</Project>
