<Project>
    <PropertyGroup>                
        <Nullable>enable</Nullable>
        <Deterministic>true</Deterministic>
        <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningsAsErrors>$(WarningsAsErrors);nullable</WarningsAsErrors>
    </PropertyGroup>
</Project>