<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.Tools" Version="2.83.0" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="Schemas\Proto\midora-common-v1.proto"
              GrpcServices="None"
              AdditionalProtocArguments="--csharp_opt=internal_access" />
    <Protobuf Include="Schemas\Proto\midora-event-instrument-v1.proto"
              GrpcServices="None"
              AdditionalProtocArguments="--csharp_opt=internal_access" />
    <Protobuf Include="Schemas\Proto\midora-logical-track-v1.proto"
              GrpcServices="None"
              AdditionalProtocArguments="--csharp_opt=internal_access" />
    <Protobuf Include="Schemas\Proto\midora-pure-midi-v1.proto"
              GrpcServices="None"
              AdditionalProtocArguments="--csharp_opt=internal_access" />
    <Content Include="Schemas\Json\*.schema.json"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Schemas\Proto\*.descriptor.sha256"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Midora.Persistence.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Midora.Domain\Midora.Domain.csproj" />
  </ItemGroup>
</Project>
